### ISSUE TITLE
Ubuntu 18.04 compiling errors

### ISSUE THREAD

**Issue by KarpHaus** [fbergo/eboard#1]
Hello,
I've downloaded the latest version of eboard here. 
./configure returns 3 no :+1: 
checking for TCP_NODELAY in netinet/in.h... no
checking for SOL_TCP in netinet/in.h... no
checking for IPPROTO_TCP in netinet/tcp.h... no

When I use 'make', at the end of the compilation I get several pages of error messages.
makefile:45: recipe for target 'eboard' failed
make: *** [eboard] Error 1

**Comment by fbergo** [comment]
Some of these TCP related messages returning no is not an issue. If all return no, you are missing the libc header files, usually part of the libc6-dev package in ubuntu 18. If you are missing this package, you probably don't have the other required development libraries either. I am not a ubuntu user and I am unable to help you with the exact package names for the dependencies (you will need the development packages for GTK+ >= 2.4.0, libpng, libstdc++, gstreamer >= 1.2.0). It is impossible to diagnose the error without the exact error messages.

**Comment by KarpHaus** [comment]
I used the following command line in order to provide a full log "make -k >error.txt 2>&1"
Sorry for the size but I am not an expert ;) I hope you will find what is wrong
LInk for the error log file :
https://framadrop.org/r/U2qteoiId2#vPgkWr2Dj6RbjMK8wdS0gjEwEo4BWwb5huwu/GIadYc=

**Comment by fbergo** [comment]
You don't have the development packages for GTK 2.x installed. The configure script should have told you that.
