### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by mgautam98** [fbergo/eboard#13]
If you have any plans for implementing new features then I would like to contribute.

**Comment by fbergo** [comment]
I am no longer actively working on this project and I have no intention of implementing new features. I am still around and will accept patches for bugfixes if they are submitted. eboard is written is very old C++ (C++98), and is based on an outdated GUI toolkit (GTK 2). Its main purpose was to be an interface for FICS, which also has been largely superseded by web-based chess servers such as lichess and chess.com.
