### ISSUE TITLE
Passing custom build flags

### ISSUE THREAD

**Issue by apoleon** [fbergo/eboard#4]
eboard's build system does not seem to support custom build flags. It would be nice if it recognized environment variables like CXXFLAGS, CPPFLAGS and LDFLAGS.

https://gist.github.com/apoleon/159fc0802ff8ef8d114c5a5b85ba909f

**Comment by fbergo** [comment]
I'll take a better look in the next few days, I'd rather force -O6 when nothing is provided.

**Comment by apoleon** [comment]
Sure, that's fine. I have updated the patch and added -O6 back. At the moment I don't know why it is added twice to the commandline though

https://gist.github.com/apoleon/52bf6c0ba3c68587e513d9f2ef8cb32b

**Comment by fbergo** [comment]
I have committed a similar idea. Reason for the duplication of -O6 in your patch: the first argument of join is the separator, the result of join('-O6',' a ',' b ', 'c ') is "a -O6 b -O6 c".
